<a href="https://colab.research.google.com/github/Bhagyanandinipillikalla/BloomBox/blob/main/Numpy_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
import numpy as np

def time_calculator(func):
    def wrapper(*args,**kwargs):
        start=time.time()
        result=func(*args, **kwargs)
        end=time.time()
        print(f"Execution Time:{end-start:.6f} seconds")
        return result
    return wrapper

@time_calculator
def basic_arithmetic(a, b):
    try:
        print("---Basic Arithmetic operations---")
        print("Addition:", np.add(a, b))
        print("Subtraction:", np.subtract(a, b))
        print("Multiplication:", np.multiply(a, b))
        print("Division:", np.divide(a, b))
        print("Power:", np.power(a, b))
    except Exception as e:
        print(e)

@time_calculator
def statistical_operations(a):
    print("---Statistical Operations---")
    print("Mean:", np.mean(a))
    print("Median:", np.median(a))
    print("Standard deviation:", np.std(a))
    print("Variance:", np.var(a))
    print("Minimum:", np.min(a))
    print("Maximum:", np.max(a))
    print("Sum:", np.sum(a))
    print("Product:", np.prod(a))
    print("Shape:", a.shape)
    print("Size:", a.size)
    print("Data type:", a.dtype)

@time_calculator
def array_manipulation(a):
    try:
      print("---Array manipulation---")
      n = a.size

      print("\n===== 2D RESHAPES =====")
      for i in range(1, n + 1):
          if n % i == 0:
              print(f"\nShape: ({i}, {n//i})")
              print(a.reshape(i, n//i))

      print("\n===== 3D RESHAPES =====")
      for i in range(1, n + 1):
          if n % i == 0:
              for j in range(1, n + 1):
                  if (i * j) <= n and n % (i * j) == 0:
                      k = n // (i * j)
                      print(f"\nShape: ({i}, {j}, {k})")
                      print(a.reshape(i, j, k))
    except Exception as e:
      print(e)

    print("Sorting:", np.sort(a))
    print("Reverse Sorting:", np.sort(a)[::-1])
    print("Unique Value:", np.unique(a))
    print("First Element:", a[0])
    print("Last Element:", a[-1])

    mean = np.mean(a)
    print("Greater than mean:", a[a > mean])

while True:
    print('=' * 33)
    print('1. Basic Arithmetic operations')
    print('2. Statistical Operations')
    print('3. Array Manipulation Operations')
    print('4. Exit')
    print('=' * 33)

    choice = input("Enter Your Choice(1-4): ")

    if choice == "1":
        a = np.array(list(map(int, input("Enter Element a: ").split())))
        b = np.array(list(map(int, input("Enter Element b: ").split())))
        basic_arithmetic(a, b)

    elif choice == "2":
        a = np.array(list(map(int, input("Enter Element: ").split())))
        statistical_operations(a)

    elif choice == "3":
        a = np.array(list(map(int, input("Enter Element: ").split())))
        array_manipulation(a)

    elif choice == "4":
        print("Exiting")
        break

    else:
        print("Invalid Choice")




1. Basic Arithmetic operations
2. Statistical Operations
3. Array Manipulation Operations
4. Exit
Enter Your Choice(1-4): 3
Enter Element: 5 6 7 7
---Array manipulation---
===== 2D RESHAPES =====

Shape: (1, 4)
[[5 6 7 7]]

Shape: (2, 2)
[[5 6]
 [7 7]]

Shape: (4, 1)
[[5]
 [6]
 [7]
 [7]]
===== 3D RESHAPES =====

Shape: (1, 1, 4)
[[[5 6 7 7]]]

Shape: (1, 2, 2)
[[[5 6]
  [7 7]]]

Shape: (1, 4, 1)
[[[5]
  [6]
  [7]
  [7]]]

Shape: (2, 1, 2)
[[[5 6]]

 [[7 7]]]

Shape: (2, 2, 1)
[[[5]
  [6]]

 [[7]
  [7]]]

Shape: (4, 1, 1)
[[[5]]

 [[6]]

 [[7]]

 [[7]]]
Sorting: [5 6 7 7]
Reverse Sorting: [7 7 6 5]
Unique Value: [5 6 7]
First Element: 5
Last Element: 7
Greater than mean: [7 7]
Execution Time:0.000963 seconds
1. Basic Arithmetic operations
2. Statistical Operations
3. Array Manipulation Operations
4. Exit
Enter Your Choice(1-4): 4
Exiting
